### ISSUE TITLE
Footstep sounds play in the air while flying in creative.

### ISSUE THREAD

**Issue by djmrFunnyMan** [Sollace/Presence-Footsteps#303]
(Doesn't affect spectator)
When you're flying in creative, and come to a quick stop, you'll hear stone footstep sounds.
For ease of reproduction use tweakeroo, and set custom fly deceleration to 0. However I can confirm that the issue is not caused by the mod and I have ran into this many times in vanilla. 

https://github.com/Sollace/Presence-Footsteps/assets/68905776/b67a542f-40c5-49d6-99af-bc682e2e6c4d

**Comment by Sollace** [comment]
What version of Presence Footsteps do you have installed?

**Comment by djmrFunnyMan** [comment]
1.11.3

**Comment by djmrFunnyMan** [comment]
Here's me reproducing it with vanilla movement without tweakeroo. 

https://github.com/Sollace/Presence-Footsteps/assets/68905776/a3509b20-e984-4e70-984f-65e024a21d43

If you can't reproduce it... honestly I won't be surprised. Presence Footsteps has been acting extremely weird for me. That issue with armor stands making nearby blocks default to footstep sounds disappeared for me a few days later despite me changing nothing. I ran into an issue where all slabs would play stone sounds/no sounds but after restarting MC the issue was gone. Kinda odd.

**Comment by Sollace** [comment]
I could never reproduce any of these issues so I don't really know what you're doing that causing it to act strange.

Armor stands _are_ supposed to produce stone sounds when you walk in the same block as them, though.

**Comment by Sollace** [comment]
Footsteps in mid-air was already fixed as well. https://github.com/Sollace/Presence-Footsteps/commit/470514f054b29466229edb5d9083cc9277d363fa

**Comment by djmrFunnyMan** [comment]
Idk the issues still occurs with no other mods so it's not that. Are you on the fabric version like I am?

**Comment by Sollace** [comment]
Of course I am

**Comment by pajicadvance** [comment]
I haven't experienced this issue since the latest update. While creating my modpack I was initially using 1.9.2 and it happened all the time, after updating to 1.9.3 it was completely gone. Same experience with 1.11.3.

**Comment by Sollace** [comment]
> I haven't experienced this issue since the latest update. While creating my modpack I was initially using 1.9.2 and it happened all the time, after updating to 1.9.3 it was completely gone. Same experience with 1.11.3.

So you don't have it with 1.11.3?

**Comment by pajicadvance** [comment]
> So you don't have it with 1.11.3?

Yes, I don't have the issue in both 1.9.3 and 1.11.3.
